name: Build app
on: push
jobs:
  ##### Analyze app #####
  analyze-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Analyze code, test and build
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release

      - name: Release
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk